spring:
  application:
    name: challenge-base
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    username: postgres
    password: password01
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  packages-to-scan: com.challenge.banregio.controller
  paths-to-match: /api/**
